Repository openshift-agent-team/fleeting, pull requests merged in 2022-03, with the labels that each got.

#5 Run assisted-service only on pre-identified node0
  Makefile
  README.md
  cmd/main.go
  data/ignition/files/usr/local/bin/common.sh
  data/ignition/files/usr/local/bin/set-node-zero.sh
  data/ignition/files/usr/local/share/assisted-service/configmap.yml
  data/ignition/systemd/units/assisted-service.service
  data/ignition/systemd/units/node-zero.service
  pkg/imagebuilder/content.go
  pkg/imagebuilder/embed_ignition.go
Labels: approved

#8 Rename assisted-installer pod to assisted-service
  data/ignition/files/usr/local/share/assisted-service/pod.yml
  data/ignition/systemd/units/assisted-service.service
Labels: approved, lgtm

#10 NO-ISSUE Increase assisted-service start timeout
  data/ignition/systemd/units/assisted-service.service
Labels: approved, lgtm

#9 AGENT-43 Fetch infra-env-id before host registration
  data/ignition/files/usr/local/bin/start-agent.sh
  data/ignition/systemd/units/agent.service
Labels: approved, lgtm

#7 AGENT-37 Create cluster and infra-env using assisted-service REST-API
  README.md
  data/ignition/files/usr/local/bin/common.sh
  data/ignition/files/usr/local/bin/create-cluster-and-infra-env.sh
  data/ignition/systemd/units/create-cluster-and-infra-env.service
  go.mod
  go.sum
  pkg/imagebuilder/content.go
  pkg/manifests/clusterdeployment.go
  pkg/manifests/infraenv.go
Labels: approved, lgtm

#14 Add Andrea and Bob to OWNERS
  OWNERS
Labels: approved, lgtm, do-not-merge/invalid-owners-file

#15 Exit on manifest file errors
  pkg/manifests/clusterdeployment.go
  pkg/manifests/infraenv.go
  pkg/manifests/manifests.go
Labels: approved, lgtm

#12 AGENT-38: Automate cluster installation
  .gitignore
  data/ignition/files/usr/local/bin/start-cluster-installation.sh
  data/ignition/systemd/units/start-cluster-installation.service
  pkg/imagebuilder/content.go
Labels: approved, lgtm

#18 Fix function name
  pkg/manifests/clusterdeployment.go
Labels: approved, lgtm
